name: Checkstyle

on:
  push:
    branches: [ main ]
  pull_request:
    branches:

permissions:
  contents: read

jobs:
  checkstyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'testtool'
        checkstyle_config: 'config/checkstyle/checkstyle.xml'
        workdir: 'src/main'
        fail_on_error: false
        level: error
