name: junit test & checkstyle & spotbugs & code coverage

on:
  workflow_dispatch:
  push:
    branches: [ feature/summarizing_all_ci ]
  pull_request:
    branches:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Docker run
        run: docker compose up -d
      - name: Test with Gradle
        run: ./gradlew test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
          checkstyle_config: 'config/checkstyle/exclude.xml'
          workdir: 'src/main'
          level: error
      - name: Run SpotBugs
        run: ./gradlew spotbugsMain
      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test results
          path: build/reports/spotbugs/main.html
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          webhook: https://hooks.slack.com/services/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
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
